apiVersion: v1
kind: Service
metadata:
  name: aide-api-claims-service
spec:
  selector:
    app: aide-api-claims
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer