apiVersion: apps/v1
kind: Deployment
metadata:
  name: aide-jobs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aide-jobs
  template:
    metadata:
      labels:
        app: aide-jobs
    spec:
      imagePullSecrets: 
        - name: my-registry-key
      containers:
        - name: aide-jobs-node
          image: aideguru/aide-hangfire-worker:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: K8sDev
            - name: AIDE_DEV_NAME
              value: Primo
            - name: TZ
              value: America/Los_Angeles